### ISSUE TITLE
Examples: scollbars.html

### ISSUE THREAD

**Issue by breezefaith** [jgraph/mxgraph2#50] opened 2020-09-11 00:43 UTC
I encountered such a problem, but limited ability, I did not find out why.

![image](https://user-images.githubusercontent.com/20924601/92832436-3be5fd00-f40a-11ea-9419-731cf92dc0f7.png)

**Comment by tbouffard** [comment] 2020-09-15 21:28
Duplicate of https://github.com/jgraph/mxgraph/issues/462 created on 2020-06-07. 
Please close this issue.

**Comment by davidjgraph** [comment] 2020-09-15 22:07
Duplicate of https://github.com/jgraph/mxgraph/issues/462

**Closed by davidjgraph** 2020-09-15 22:07 UTC
